language: python
python: 
- 3.4
script: python3 test_fruits.py

#installation
  #before install

  #install

#script
  #before_script
  #script

#after script
  #after sucess
  #after failure

#deploy
  #before deploy
  #deploy
  #after deploy
  
  #safelist
branches:
  only:
  - master
  - /[upt][a-q]*[t]/

#blocklist
branches:
  except:
  - opt
#comments 
